spring:
  datasource:
    url: jdbc:mysql://${news.datasource.ip}:3306/sys_user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${news.datasource.username}
    password: ${news.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
