spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        ## auth
        - id: news-uaa
          uri: lb://news-uaa
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        ## admin
        - id: news-user
          uri: lb://news-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        ## cms
#        - id: yc-cms
#          uri: lb://yc-cms
#          predicates:
#            - Path=/cms/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=1
        ## file
#        - id: yc-file
#          uri: lb://yc-file
#          predicates:
#            - Path=/file/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=1
# 打开客户端的监控
management:
  endpoints:
    sensitive: false
    web:
      exposure:
        include: '*'